---
apiVersion: v1
kind: Service
metadata:
  name: smartworkx-postgres
  labels:
    app: smartworkx-postgres
    visualize: "true"
    name: "smartworkx-postgres"
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: smartworkx-postgres
  type: "NodePort"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: smartworkx-postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: smartworkx-postgres
        visualize: "true"
        name: "smartworkx-postgres"
    spec:
      containers:
      - name: smartworkx-postgres
        image: postgres:9.6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432