---
apiVersion: v1
kind: Service
metadata:
  name: smartworkx-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: '5432'
---
apiVersion: v1
kind: Endpoints
metadata:
  name: smartworkx-postgres
subsets:
  - addresses:
      - ip: 35.195.145.211
    ports:
      - port: 5432
        name: '5432'